# Generated by Django 4.2.11 on 2024-03-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('bot', 'Bot'), ('user', 'User')], max_length=20),
        ),
    ]
