# Generated by Django 4.2.11 on 2024-03-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librot_app', '0002_alter_message_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='completion_tokens',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='prompt_tokens',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='total_tokens',
            field=models.IntegerField(null=True),
        ),
    ]
